title: Multikernel Technologies
email: contact@multikernel.io
description: >-
  Advanced kernel-based security solutions.
baseurl: ""
url: "https://multikernel.io" # Set to your custom domain

# Build settings
markdown: kramdown
encoding: utf-8
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed

# Custom domain
github_pages:
  cname: multikernel.io

# Exclude unnecessary files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
