title: Multikernel Technologies
email: contact@multikernel.io
description: >-
  Advanced kernel-based security solutions.
baseurl: ""
url: "https://multikernel.io" # Set to your custom domain

# Jekyll configuration
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections and defaults
collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins will be handled by GitHub Pages

# Custom domain
github_pages:
  cname: multikernel.io

# Exclude unnecessary files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
